<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EtudiantSeeder extends Seeder
{
    public function run()
    {
        DB::table('etudiants')->insert([
            ['matricule' => '21P156', 'nom' => 'ABADA', 'prenom' => 'GEORGES ATYLLIO', 'classe_id' => 2],
            ['matricule' => '23P756', 'nom' => 'ABAKAR', 'prenom' => 'DJIBRILA', 'classe_id' => 2],
            ['matricule' => '21P356', 'nom' => 'ADA BALLA', 'prenom' => 'RENEE-FRANCINE', 'classe_id' => 2],
            ['matricule' => '20P200', 'nom' => 'AKOA NKENGUE', 'prenom' => 'AIME THIBAUT', 'classe_id' => 2],
            ['matricule' => '23P750', 'nom' => 'ANTOINE', 'prenom' => 'EMMANUEL', 'classe_id' => 2],
            ['matricule' => '21P233', 'nom' => 'BADA', 'prenom' => 'RODOLPHE ANDRE', 'classe_id' => 2],
            ['matricule' => '21P320', 'nom' => 'BAKOTCHA KAMTCHE', 'prenom' => 'HERVE LOIC', 'classe_id' => 2],
            ['matricule' => '21P301', 'nom' => 'BEKONO BINDUGA', 'prenom' => 'FLORIAN DONALD', 'classe_id' => 2],
            ['matricule' => '21P091', 'nom' => 'BENGONO AMVELA', 'prenom' => 'NATHAN', 'classe_id' => 2],
            ['matricule' => '20P286', 'nom' => 'BIHAY', 'prenom' => 'RAPHAËL', 'classe_id' => 2],
            ['matricule' => '19P300', 'nom' => 'BISSONO NYAMDI', 'prenom' => 'JEAN-MARIE VICTOR', 'classe_id' => 2],
            ['matricule' => '21P372', 'nom' => 'BOUIYODA', 'prenom' => 'JOSEPH', 'classe_id' => 2],
            ['matricule' => '21P033', 'nom' => 'CESSU CHOUMESSI', 'prenom' => 'MAXIME', 'classe_id' => 2],
            ['matricule' => '21P344', 'nom' => 'KABEYENE TOUALEU', 'prenom' => 'CHLOE KERONNE', 'classe_id' => 2],
            ['matricule' => '21P169', 'nom' => 'DANGA PATCHOUM', 'prenom' => 'BLONDE', 'classe_id' => 2],
            ['matricule' => '21P038', 'nom' => 'DJOKO DJODOM', 'prenom' => 'SYNTIA LOANA', 'classe_id' => 2],
            ['matricule' => '21P360', 'nom' => 'DJONGO FOKOU', 'prenom' => 'ARIEL SHARON', 'classe_id' => 2],
            ['matricule' => '21P287', 'nom' => 'DJOUNKENG NGUEFACK', 'prenom' => 'ELEONOR CASSIN', 'classe_id' => 2],
            ['matricule' => '21P107', 'nom' => 'DONCHI', 'prenom' => 'TRESOR LEROY', 'classe_id' => 2],
            ['matricule' => '23P751', 'nom' => 'FEZEU YOUNDJE', 'prenom' => 'FREDY CLINTON', 'classe_id' => 2],
            ['matricule' => '21P011', 'nom' => 'FOLONG TAFOUKEU', 'prenom' => 'ZIDANE', 'classe_id' => 2],
            ['matricule' => '21P021', 'nom' => 'FOMEKONG TAMDJI', 'prenom' => 'JONATHAN BACHELARD', 'classe_id' => 2],
            ['matricule' => '21P188', 'nom' => 'HASSANA', 'prenom' => 'ZOUHEIRIYYA MOHAMADOU', 'classe_id' => 2],
            ['matricule' => '21P254', 'nom' => 'KAMDEM POUOKAM', 'prenom' => 'IVANN HAROLD', 'classe_id' => 2],
            ['matricule' => '21P308', 'nom' => 'KAMGA CHEUKO', 'prenom' => 'FRANKLIN DAVY', 'classe_id' => 2],
            ['matricule' => '21P335', 'nom' => 'KENFACK NOUMEDEM', 'prenom' => 'FRANCK ULRICH', 'classe_id' => 2],
            ['matricule' => '21P027', 'nom' => 'KENGALI FEGUE', 'prenom' => 'PACOME', 'classe_id' => 2],
            ['matricule' => '21P127', 'nom' => 'KENGNE TUEGUEM', 'prenom' => 'FRESNEL GRACE', 'classe_id' => 2],
            ['matricule' => '23P752', 'nom' => 'KOGHENE', 'prenom' => 'LADZOU ERIC', 'classe_id' => 2],
            ['matricule' => '21P039', 'nom' => 'KOMGUEM OUANDI', 'prenom' => 'ISIS HELCIAS', 'classe_id' => 2],
            ['matricule' => '21P082', 'nom' => 'KOUASSI DE YOBO', 'prenom' => 'GILBERT BRYAN', 'classe_id' => 2],
            ['matricule' => '21P190', 'nom' => 'KOUDJOU TIEMIGNI', 'prenom' => 'VICRAND ARMEL', 'classe_id' => 2],
            ['matricule' => '21P130', 'nom' => 'KUATE KAMGA', 'prenom' => 'BRAYAN ARMEL', 'classe_id' => 2],
            ['matricule' => '21P296', 'nom' => 'LADO', 'prenom' => 'SAHA', 'classe_id' => 2],
            ['matricule' => '20P231', 'nom' => 'LAFRIC', 'prenom' => 'SHAGGY AKONO', 'classe_id' => 2],
            ['matricule' => '21P187', 'nom' => 'LEMOBENG NGOUANE', 'prenom' => 'BELVIANE', 'classe_id' => 2],
            ['matricule' => '21P272', 'nom' => 'MAFFO FONKOU', 'prenom' => 'NATACHA BRENDA', 'classe_id' => 2],
            ['matricule' => '21P340', 'nom' => 'MBASSI EWOLO', 'prenom' => 'LOÏC ARON', 'classe_id' => 2],
            ['matricule' => '21P110', 'nom' => 'MBEUYO BEUFU', 'prenom' => 'AUDREY SANDRA', 'classe_id' => 2],
            ['matricule' => '23P770', 'nom' => 'MBIAMY NGAMENI', 'prenom' => 'STEVEN LOIC', 'classe_id' => 2],
            ['matricule' => '21P269', 'nom' => 'MBOCK', 'prenom' => 'JEAN DANIEL', 'classe_id' => 2],
            ['matricule' => '21P072', 'nom' => 'MBOGNENG', 'prenom' => 'TETSIEBOU JUNIOR', 'classe_id' => 2],
            ['matricule' => '21P369', 'nom' => 'MEKIAGE', 'prenom' => 'OLIVIER', 'classe_id' => 2],
            ['matricule' => '21P093', 'nom' => 'MENGOSSO MESSELE', 'prenom' => 'NICOLAS', 'classe_id' => 2],
            ['matricule' => '21P246', 'nom' => 'MOGOU', 'prenom' => 'IGOR GREEN', 'classe_id' => 2],
            ['matricule' => '21P128', 'nom' => 'MOMBO-DINGBA', 'prenom' => 'EMMANUEL', 'classe_id' => 2],
            ['matricule' => '19P162', 'nom' => 'MOUKOKO MOUNGOLE', 'prenom' => 'ENZO RAHAN CHARLES', 'classe_id' => 2],
            ['matricule' => '21P274', 'nom' => 'NANDA', 'prenom' => 'WANDA', 'classe_id' => 2],
            ['matricule' => '21P174', 'nom' => 'NANFAH', 'prenom' => 'ELSA', 'classe_id' => 2],
            ['matricule' => '20P292', 'nom' => 'NDONGO AMBASSA', 'prenom' => 'INGRID VANELLA', 'classe_id' => 2],
            ['matricule' => '21P273', 'nom' => 'NEGOUM WOUATEDEM', 'prenom' => 'YVES ARTHUR', 'classe_id' => 2],
            ['matricule' => '21P014', 'nom' => 'NGAH NDONGO', 'prenom' => 'ESTELLE CLOTILDE', 'classe_id' => 2],
            ['matricule' => '21P012', 'nom' => 'NGANTA', 'prenom' => 'YATCHOUA ANGE PACIFIQUE', 'classe_id' => 2],
            ['matricule' => '21P149', 'nom' => 'NGEUKEU', 'prenom' => 'MELI AUDAIN', 'classe_id' => 2],
            ['matricule' => '21P279', 'nom' => 'NGHOGUE TAPTUE', 'prenom' => 'FRANCK RODDIER', 'classe_id' => 2],
            ['matricule' => '21P089', 'nom' => 'NGO BASSOM', 'prenom' => 'ANNE ROSALIE', 'classe_id' => 2],
            ['matricule' => '21P336', 'nom' => 'NGOM', 'prenom' => 'CHRISTINE CARELLE ANGE', 'classe_id' => 2],
            ['matricule' => '21P086', 'nom' => 'NGOUPAYE', 'prenom' => 'DJIO THIERRY', 'classe_id' => 2],
            ['matricule' => '20P147', 'nom' => 'NGUEMNE NGUEPNAND', 'prenom' => 'KELIAN DARRYL', 'classe_id' => 2],
            ['matricule' => '21P373', 'nom' => 'NGUIFFO NGAKOU', 'prenom' => 'RICK VARNEL', 'classe_id' => 2],
            ['matricule' => '21P070', 'nom' => 'NJIOCKOU', 'prenom' => 'HAIRBEL CALVINO', 'classe_id' => 2],
            ['matricule' => '21P262', 'nom' => 'NKOUATHIO KEMNHOU', 'prenom' => 'GURVAN RONEL', 'classe_id' => 2],
            ['matricule' => '23P753', 'nom' => 'NOMO BODIANGA', 'prenom' => 'GABRIEL NASAIRE JUNIO', 'classe_id' => 2],
            ['matricule' => '21P284', 'nom' => 'NOUKOUA TATMFO', 'prenom' => 'MAEVA SANDY', 'classe_id' => 2],
            ['matricule' => '21P318', 'nom' => 'NOUNDJEU NOUBISSIE', 'prenom' => 'FRANCK TRESOR', 'classe_id' => 2],
            ['matricule' => '21P223', 'nom' => 'NTYE EBO\'O', 'prenom' => 'NINA LAISSA', 'classe_id' => 2],
            ['matricule' => '21P382', 'nom' => 'OBAMA', 'prenom' => 'CLEMENT', 'classe_id' => 2],
            ['matricule' => '18P156', 'nom' => 'OSSOMBE ONDO', 'prenom' => 'WILFRED JOVANI', 'classe_id' => 2],
            ['matricule' => '20P239', 'nom' => 'SHEY', 'prenom' => 'CYRILLE NJETA', 'classe_id' => 2],
            ['matricule' => '21P275', 'nom' => 'SIBEFEU CHIMBA', 'prenom' => 'EMMANUEL CARLOS', 'classe_id' => 2],
            ['matricule' => '21P024', 'nom' => 'SIMO', 'prenom' => 'ALAN SOREL', 'classe_id' => 2],
            ['matricule' => '21P172', 'nom' => 'SIMO TCHIMCHUA', 'prenom' => 'LINE CHARIELLE', 'classe_id' => 2],
            ['matricule' => '21P050', 'nom' => 'SINGHE PENKA', 'prenom' => 'HENDRIX DONAVAN', 'classe_id' => 2],
            ['matricule' => '21P034', 'nom' => 'SOLEFACK TEMGOUA', 'prenom' => 'JUDICAEL KROS', 'classe_id' => 2],
            ['matricule' => '23P797', 'nom' => 'FOTSEU TAMO', 'prenom' => 'STEVE ULRICH', 'classe_id' => 2],
            ['matricule' => '21P073', 'nom' => 'TCHASSI', 'prenom' => 'DANIEL', 'classe_id' => 2],
            ['matricule' => '21P061', 'nom' => 'TSAMO KUEFACK', 'prenom' => 'FLORETTE MIROSLAVA', 'classe_id' => 2],
            ['matricule' => '21P018', 'nom' => 'VUIDE OUENDEU', 'prenom' => 'FRANCK JORDAN', 'classe_id' => 2],
            ['matricule' => '21P278', 'nom' => 'WADOH TCHINDA', 'prenom' => 'PAVEL DIOR', 'classe_id' => 2],
            ['matricule' => '21P030', 'nom' => 'WANDJI', 'prenom' => 'EMMANUEL JUNIOR', 'classe_id' => 2],
            ['matricule' => '21P081', 'nom' => 'WATCHO NKOANKE', 'prenom' => 'WILLY BERLUS', 'classe_id' => 2],
            ['matricule' => '21P228', 'nom' => 'WOTCHOKO NGATCHEU', 'prenom' => 'YOHAN', 'classe_id' => 2],
            ['matricule' => '20P094', 'nom' => 'WOTO TALLA', 'prenom' => 'HUGUES MARTIAL', 'classe_id' => 2],
            ['matricule' => '21P417', 'nom' => 'YIMBOU THEDOM', 'prenom' => 'JUDE EMMANUELLI', 'classe_id' => 2],
            ['matricule' => '22P142', 'nom' => 'YIMDJO TSASSIM', 'prenom' => 'JASMIN', 'classe_id' => 2],
            ['matricule' => '21P240', 'nom' => 'YOMBA', 'prenom' => 'MERVEILLE ROSE', 'classe_id' => 2],
        ]);
    }
}