package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EstpresentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstpresentAllPropertiesEquals(Estpresent expected, Estpresent actual) {
        assertEstpresentAutoGeneratedPropertiesEquals(expected, actual);
        assertEstpresentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstpresentAllUpdatablePropertiesEquals(Estpresent expected, Estpresent actual) {
        assertEstpresentUpdatableFieldsEquals(expected, actual);
        assertEstpresentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstpresentAutoGeneratedPropertiesEquals(Estpresent expected, Estpresent actual) {
        assertThat(expected)
            .as("Verify Estpresent auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstpresentUpdatableFieldsEquals(Estpresent expected, Estpresent actual) {
        assertThat(expected)
            .as("Verify Estpresent relevant properties")
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstpresentUpdatableRelationshipsEquals(Estpresent expected, Estpresent actual) {
        assertThat(expected)
            .as("Verify Estpresent relationships")
            .satisfies(e -> assertThat(e.getHoraire()).as("check horaire").isEqualTo(actual.getHoraire()))
            .satisfies(e -> assertThat(e.getEtudiant()).as("check etudiant").isEqualTo(actual.getEtudiant()));
    }
}
