package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class HoraireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoraireAllPropertiesEquals(Horaire expected, Horaire actual) {
        assertHoraireAutoGeneratedPropertiesEquals(expected, actual);
        assertHoraireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoraireAllUpdatablePropertiesEquals(Horaire expected, Horaire actual) {
        assertHoraireUpdatableFieldsEquals(expected, actual);
        assertHoraireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoraireAutoGeneratedPropertiesEquals(Horaire expected, Horaire actual) {
        assertThat(expected)
            .as("Verify Horaire auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoraireUpdatableFieldsEquals(Horaire expected, Horaire actual) {
        assertThat(expected)
            .as("Verify Horaire relevant properties")
            .satisfies(e -> assertThat(e.getJour()).as("check jour").isEqualTo(actual.getJour()))
            .satisfies(e ->
                assertThat(e.getHeureDebut())
                    .as("check heureDebut")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getHeureDebut())
            )
            .satisfies(e ->
                assertThat(e.getHeureFin()).as("check heureFin").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getHeureFin())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoraireUpdatableRelationshipsEquals(Horaire expected, Horaire actual) {
        // empty method
    }
}
