package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MatiereAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAllPropertiesEquals(Matiere expected, Matiere actual) {
        assertMatiereAutoGeneratedPropertiesEquals(expected, actual);
        assertMatiereAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAllUpdatablePropertiesEquals(Matiere expected, Matiere actual) {
        assertMatiereUpdatableFieldsEquals(expected, actual);
        assertMatiereUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereAutoGeneratedPropertiesEquals(Matiere expected, Matiere actual) {
        assertThat(expected)
            .as("Verify Matiere auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereUpdatableFieldsEquals(Matiere expected, Matiere actual) {
        assertThat(expected)
            .as("Verify Matiere relevant properties")
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatiereUpdatableRelationshipsEquals(Matiere expected, Matiere actual) {
        assertThat(expected)
            .as("Verify Matiere relationships")
            .satisfies(e -> assertThat(e.getHoraire()).as("check horaire").isEqualTo(actual.getHoraire()))
            .satisfies(e -> assertThat(e.getEnseignant()).as("check enseignant").isEqualTo(actual.getEnseignant()))
            .satisfies(e -> assertThat(e.getClasses()).as("check classes").isEqualTo(actual.getClasses()))
            .satisfies(e -> assertThat(e.getEtudiants()).as("check etudiants").isEqualTo(actual.getEtudiants()));
    }
}
